### ISSUE TITLE
Operators Namespace

### ISSUE THREAD

**Issue by markusspitzli** [nolar/kopf#1014]
### Keywords

namespace

### Problem

I want to know how it is possible to see the current namespace of the kopf operator during startup.

**Comment by bobh66** [comment]
https://kopf.readthedocs.io/en/stable/cli/#scope-options

**Comment by markusspitzli** [comment]
I know that docu and it does not answer my questions. 
I run the operator in namespace x and it should monitor all namespaces on the cluster. How do I get the information in which namespace the operator runs?

**Comment by bobh66** [comment]
The operator runs in the namespace that you deploy it in, if you specify one, otherwise it will run in the default namespace - https://kopf.readthedocs.io/en/stable/deployment/#cluster-deployment

**Comment by markusspitzli** [comment]
I know that. What I dont know is how I receive this information within the kopf operator. Is there some sort of an environment variable that I can get the information from or does the kopf.on.startup deliver this information?

**Comment by bobh66** [comment]
I don't believe that's available by default but you can use the Downward API to set an env variable with the deployed namespace for the pod to access:  https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-fieldRef

**Comment by markusspitzli** [comment]
thanks. that helped.
