### ISSUE TITLE
Document how to debug kopf

### ISSUE THREAD

**Issue by lkoniecz** [nolar/kopf#1032]
### Keywords

debugger, debug, debugging

### Problem

I want to start kopf with debugger mode so that I can attach to it with me IDE and debug the code.
Is it doable but not yet documented?

regards

**Comment by lkoniecz** [comment]
for those who are as blind as me
https://github.com/nolar/kopf/blob/main/DEVELOPMENT.md#pycharm--ides

**Comment by asteven** [comment]
@lkoniecz If you consider this issue solved, please close it.
