### ISSUE TITLE
How to update status subresource during handler

### ISSUE THREAD

**Issue by ps-jay** [nolar/kopf#514]
## Question

Can I update the status subresource with arbitrary data (potentially multiple times) during the handler execution?

#### Background:

I'm trying to build an operator that will create/update/delete AWS Cloudformation stacks.

At the moment, when the custom resource describing the stack is created/updated/deleted, I've got kopf catching the event and calling AWS's API's to do the same to the Cloudformation stack - and then _waiting_ for the stack to finish creating/updating/deleting.

I was thinking that it would be good to be able to update the status of the custom resource during the action, and so I'm trying to figure out how to use `patching.patch_obj()` to do this.

I've tried calling `patch_obj()` directly like so:
```
patch_obj(
    resource=kwargs['cause'].resource,
    body=body,
    patch={'status': {'cloudformation_deployment': {'status': cfn_status}}})
```

But this never returns, so I'm doing something wrong!

Can you guide me on how to update the status multiple times _during_ a handler execution?

---

Side note: is a "long running" handler (e.g. while it waits for AWS to finish .. 1 - 30 minutes for example) the right way to go at all?

Or should I be doing some kind of scheduled polling of AWS to discover where Cloudformation is up to, and update the status via those results?

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

I thought #320 might help, but it doesn't address updating the status multiple times per handler execution.

## Keywords

status
patching

**Comment by nolar** [comment]
@ps-jay Hello. Sorry for the late response. 

First things first: `patch_obj()` is an internal routine that is not supposed to be used outside of the framework. Only things exposed in `kopf/__init__.py` are supposed to be used in the operators. In the future, the internal way of communicating with K8s API can change without maintaining backward compatibility. To implement patching explicitly, please use any of the K8s client libraries: e.g. [pykube-ng](https://github.com/hjacobs/pykube) or the Kubernetes official client.

Second, answering your other question: on-creation/update/deletion handlers are supposed to be relatively short, i.e. less than or at the scale of a second, plus-minus. Long handlers (minutes) will probably function, but will lead to unpredictable consequences. For example, a node pool for the synchronous handlers will be depleted, preventing new handlers for other resources from being called. And certainly, even if you do the async handlers, it will prevent new handlers for the current object being handled: one object is always handled sequentially, despite that multiple distinct objects are handled in parallel.

Third, if you want the long-running handers, there is a special type for them: [daemons](https://kopf.readthedocs.io/en/latest/daemons/) & [timers](https://kopf.readthedocs.io/en/latest/timers/). Timers, however, are also supposed to be short, but the daemons can really run for any time.

These last two types of handlers are specially designed for the kind of tasks that you described: polling some extrnal resources.

For example, you can poll it every second:

```python
import kopf, requests

@kopf.timer(..., interval=1)
def poll_cf_status(spec, patch, **kwargs):
    cf_status = requests.get(id=spec.get('id'), ....)
    patch.status['message'] = '...'
```

Please note that you can modify the [`patch` kwarg](https://kopf.readthedocs.io/en/latest/kwargs/#patching) — it will be saved to the object after the handler exits. Unlike `patch_obj()`, `patch` is an official interface of Kopf and will be maintained.

Alternatively, you can implement the same logic via a daemon:

```python
import kopf, requests

@kopf.daemon(...)
def poll_cf_status(body, patch, stopped, **kwargs):
    while not stopped:
        cf_status = requests.get(...)
        stopped.wait(1.0)  # instead of time.sleep(1.0)
```

In this case, however, `patch` is useless during the run. Even if you modify it, it will be applied to the object only after the daemon exits. But you can use your API client to apply the changes yourself. Or you an make the daemon restartable. Though, to my personal opinion, this approach does not look as convincing as with the timers.

For both daemons & timers, once you reach a point where they should not be called/restarted again, you would want to stop the daemon and prevent the timer from ticking. For that, use [filters](https://kopf.readthedocs.io/en/latest/filters/). The trick is: once the object stops matching the criteria, the framework stops the daemon and timers — implicitly, you don't need to worry much about that. Lambdas would also work, but here is an example with a function, for readability:

```python
import kopf, requests

def is_not_done(body, **_) -> bool:
    return body.status.get('done')

@kopf.timer(..., interval=1, when=is_not_done)
def poll_cf_status(spec, patch, **kwargs):
    cf_status = requests.get(id=spec.get('id'), ....)
    patch.status['message'] = '...'
    patch.status['done'] = True/False
```

Same for the daemon — except that you need to notice the `stopped` kwarg change, and exit from the function. The example above will do.

**Comment by ps-jay** [comment]
Thanks for the detailed reply. 

I'll take some time to let it all sink into my head!

**Comment by ps-jay** [comment]
Thanks again for the reply.

Timers do seem perfect!
I hadn't realised that I would get an individual timer "thread" (co-routine?) per object - that makes much more sense now.

**Comment by retr0h** [comment]
@nolar thank you very much for this.  I have a question about the code you had above (posted below for clarity).

```python
import kopf, requests

def is_not_done(body, spec, **_) -> bool:
    conditions = body.status.get("conditions", [])
    condition = conditions[0]

    if condition:
        if condition["type"] == "Available" and condition["status"] == "True":
            LOG.info("Deployment is available")
            return False

    return True

@kopf.on.timer(
    "apps",
    "v1",
    "deployments",
    labels={"app": "nginx"},
    interval=1,
    when=is_not_done,
)
def poll_deployment_status(spec, patch, **kwargs):
    # return {"foo": True}
    patch.status['done'] = True/False
```

I end up getting the following error, however, I now realize I'm trying to update status on the deployment's object, where I'm wanting to update status of my custom resource, since the custom resource was responsible for creation of the deployment.

```
WARNING  Patching failed with inconsistencies: (('remove', ('status', 'done'), True, None),)
```

The goal of this timer is to watch a deployment which the operator creates and manages.  I was hoping to use the timer pattern to determine when it is available, and update status indicating the deployment is complete.
