### ISSUE TITLE
How to wait on deleting external resources before removing the finalizer

### ISSUE THREAD

**Issue by ps-jay** [nolar/kopf#541]
## Question

How can I delay the removal of the finalizer until particular external resources are deleted?

I've tried using timers, but these don't seem to fire once an object has a `deletionTimestamp` on them.

I've also tried using a daemon, but this doesn't (natively) allow for patching the `status` without exiting.

### Background

I'm trying to build an operator that will create/update/delete AWS Cloudformation stacks.
Thanks for the help provided in #514.

Ideally when the K8s object is marked for deletion I'd like to send API calls to AWS to delete the Cloudformation stack, but wait around to see that the stack does actually get deleted.

So far I've tried different variations of code, mostly variations on this style:

```
def delete(stack, logger):
    # API call to AWS to delete the stack
    # API call to AWS to describe the stack status
    return stack_status

def is_deleting(meta, **_) -> bool:
    return bool(meta.get('deletionTimestamp'))

@kopf.timer('example.com', 'v1alpha1', 'cloudformationdeployments', interval=20, when=is_deleting)
def cfn_terminate(patch, spec, status, logger, **_) -> None:
    stack = spec['stack']
    old_status = status.get('stack_status')
    if old_status != 'DELETE_COMPLETE':
        new_status = delete(stack, logger)  # API calls to AWS
        patch['status']['stack_status'] = new_status
        if new_status != old_status:
            logger.info(f"CFN stack {stack['name']} transitioned to status {new_status}")

@kopf.daemon('reece.tech', 'v1alpha1', 'cloudformationdeployments')
def monitor_for_deletion(meta, status, stopped, logger, **_):
    while not stopped:
        # This loops until either: object deleted, or, this software is gracefully exiting
        stopped.wait(10)

    if meta.get('deletionTimestamp'):
        # This loops only if the object is needed to be deleted
        while True:
            if status.get('stack_status') == 'DELETE_COMPLETE':
                break
                # Finalizer deleted when we exit this loop
            time.sleep(5)
```

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

finalizer
final
timer
daemon

**Comment by nolar** [comment]
Hello. I guess, the deletion handlers can help — they get triggered when the object is marked for deletion. They also combine normally with usual [retries, permanent & temporary error logic](https://kopf.readthedocs.io/en/latest/errors/).

```python
import kopf

@kopf.on.delete(...)
def delete_cf(**_):
    delete_cloudformation(...)

@kopf.on.delete(...)
def poll_cf_is_gone(**_):
    if not is_remote_resource_deleted():
        raise kopf.TemporaryError("Remote resource is not yet deleted, waiting.", delay=10)
```

**Comment by eshepelyuk** [comment]
Sorry for jumping into conversation, but just maybe you don't need to create custom operator for your needs, @ps-jay.

I'd suggest to evaluate this project https://crossplane.io/docs/v0.12/
Maybe you find it suitable for your needs.

**Comment by ps-jay** [comment]
Thanks @nolar, that approach is working for me.

Jumping in is okay @eshepelyuk.  I've had a look at crossplane, but I can't see where it handles Cloudformation stacks?  It seems to be focused on handling individual AWS services?  Am I mistaken?
