### ISSUE TITLE
kopf.daemon: set/update status

### ISSUE THREAD

**Issue by schlitzered** [nolar/kopf#580]
## Question

from the examples, is there a way to update status['children'] from within a daemon?

so that the output from "kubectl get kopfexamples" can be changed from within a daemon.

this is the code i am currently using:

```
@kopf.daemon('zalando.org', 'v1', 'kopfexamples', cancellation_backoff=1.0, cancellation_timeout=3.0)
async def create_fn(stopped, patch, **kwargs):
    print(f"And here we are! Starting Daemon")
    for key, value in kwargs.items():
        print(f"daemon kwargs are key: '{key}', value: {value}")

    _children = 0

    while not stopped:
        _children += 1
        patch.status['children'] = _children
        print(f"children is: {_children}")
        await asyncio.sleep(1)

    print("daemon is gone")
```

## Checklist

- [x ] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x ] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

daemon
status

**Comment by nolar** [comment]
Generally, no — and that is on purpose: Kopf is not a K8s API client library (though I start to reconsider that slowly).

The resource is better to be edited/patched by your preferred K8s API client library (let's say, pykube-ng — despite it is not async, but is good enough for this example):

```python
import kopf
import pykube

class KEX(pykube.objects.NamespacedAPIObject):
    version = 'zalando.org/v1'
    endpoint = 'kopfexamples'
    kind = 'KopfExample'

@kopf.daemon('zalando.org', 'v1', 'kopfexamples')
def dmn(stopped, name, namespace, **_):
    counter = 0
    while not stopped:
        counter += 1
        api = pykube.HTTPClient(pykube.KubeConfig.from_env())
        obj = KEX.objects(api, namespace=namespace).get_by_name(name)
        obj.patch({"status": {"counter": counter}})
        #obj.patch({"status": {"counter": counter}}, subresource='status')  # or this way
        time.sleep(1)
```

This may be somewhat annoying to mix two different libraries and approaches. Other libraries might do this better.

---

Another way would be to reconsider a forever-running daemon into a wait-apply-repeat daemon:

```python
import kopf

@kopf.daemon('zalando.org', 'v1', 'kopfexamples')
def dmn(stopped, patch, **_):

    # Spend as long as needed here.
    while not stopped and not check_for_some_condition():
        time.sleep(1)

    # Inject the data to apply to the resource, and exit immediately (by raising a special exception).
    if not stopped:  # i.e. it was the condition satisfied
        patch.status["something"] = "value"
        raise kopf.TemporaryError("Need to restart.", delay=None)
```

It will be restarted instantly. However, this trick will produce some extra logs for the daemon's restart.
Restarting is documented here: https://kopf.readthedocs.io/en/latest/daemons/#restarting

---

The best way for your example might be to use `@kopf.timer()` with a [`memo`](https://kopf.readthedocs.io/en/latest/kwargs/#in-memory-container) — unless the logic is intended to be different than in the example. Something like this (we assume that we do not use the resource itself as the storage):

```python
import kopf

@kopf.timer('zalando.org', 'v1', 'kopfexamples', interval=1)
def tmr(patch, memo, **_):
    patch.status["counter"] = memo['counter'] = memo.get('counter', 0) + 1
```

**Comment by nolar** [comment]
Also please note that `print("daemon is gone")` will not always be executed in your example. The benefit of async codebase is that the routines can be cancelled at any time (unlike sync threads). If the operator is stopping, the chances are high that the daemon will be cancelled in its `asyncio.sleep()` by injecting an exception. To catch the actual exit, you should use `try: … finally: …` or `try: … except asyncio.CancelledError: …`. This is unrelated to the question though.

**Comment by schlitzered** [comment]
thanks for the detailed answers. 

i agree that it would be nice to have a sync/async kubernetes api integrated, even if it is only a wrapper around existing libraries, so one has not to take care about login related stuff and so on.

i am currently just starting to get myself familiar with kubernetes operators.

i think i will give https://github.com/tomplus/kubernetes_asyncio a try for the moment.

thanks again.
