### ISSUE TITLE
Dropping Python 3.7: why not?

### ISSUE THREAD

**Issue by nolar** [nolar/kopf#590]
Python 3.7 support is considered to be dropped, restricting Kopf to Python >= 3.8.

Why not >= 3.9? One reason considered in #74 (for Python 3.6) was that some companies restrict their environments to LTS versions only (vendor-provided, or for any other reasons), so it is too early for such a framework-level requirement (the operators can use any versions of Python).

The latest Ubuntu LTS (20.04 since Apr'2020) contains Python 3.8 by default. And it was out there for 8 months already — enough time to upgrade and migrate.

RedHat Enterprise Linux 8 (released May'2019) commits to Python 3.6 support for the whole 8.x series, but RHEL 8.2 (Apr'2020) officially provides Python 3.8 in addition to 3.6 ([link](https://developers.redhat.com/blog/2020/06/25/red-hat-enterprise-linux-8-2-brings-faster-python-3-8-run-speeds/)).

So, there seems to be no reason to support Python 3.7 even for these restrictive use-cases.

**QUESTIONS:** 

* Can Python 3.7 support be dropped from Kopf safely?
* How will it affect you and your operators?
* Do you have a low-effort upgrade scenario in place?
* Any other considerations?

Tell us why this might be a bad idea to drop Python 3.7 support.

**Comment by MarkusH** [comment]
AFAICT, Kopf, as a framework, will only be used to build operators. They then run as some form of container "inside" Kubernetes. The operators will (unlikely?) run on some server connecting into K8s "from the outside". So, from where I'm sitting, requiring new Python versions isn't a matter of LTS support on production hosts, but rather availability of the Python version on developer machines.
