### ISSUE TITLE
Defining a pydantic model in a kopf handler file seems to break kopf startup

### ISSUE THREAD

**Issue by trondhindenes** [nolar/kopf#631]
## Long story short
If I define a pydantic class, kopf refuses to start

## Description
Steps to repro:
start out with a super-simple kopf handler file, such as:
```python
import kopf


@kopf.on.create('what.com', 'v1', 'stuffs')
def create_fn(body, **kwargs):
    print(body)


@kopf.on.update('what.com', 'v1', 'stuffs')
def update_fn(body, **kwargs):
    print(body)
```
I'm using pipenv so I'd run this with: `pipenv run kopf run "src/crawler_manager/handler.py"`. All good.

Now, expand the file with a simple pydantic model definition:

```python
import kopf
from pydantic import BaseModel, Field
from typing import Dict


class TestModel(BaseModel):
    name: str = Field(...)
    size: int
    size2: int
    
@kopf.on.create('mohawkanalytics.com', 'v1', 'stuffs')
def create_fn(body, **kwargs):
    print(json.dumps(body, indent=4, sort_keys=True))


@kopf.on.update('mohawkanalytics.com', 'v1', 'stuffs')
def update_fn(body, **kwargs):
    print(json.dumps(body, indent=4, sort_keys=True))
```

This code now throws:
```
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "src/funnel_crawler_manager/handler.py", line 9, in <module>
    class TestModel(BaseModel):
  File "pydantic/main.py", line 247, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/typing.py", line 207, in pydantic.typing.resolve_annotations
    for p in parameters:
KeyError: 'handler'
```

I have no idea why. The idea was to use a pydantic-defined model to define the CRD at if needed configure it during kopf startup (pydantic can generate openapi-compatible schemas, so this way we were hoping to maintain the CRD in code instead of in yaml).

Testing done using `pydantic==1.7.3`

I'm afraid I don't know more than this - I also don't know if the actual bug is in Pydantic or kopf.

## Environment
* Kopf version: 0.28.3
* Kubernetes version: 3.9
* Python version: 
* OS/platform:

**Comment by trondhindenes** [comment]
it looks like running kopf in module mode (`kopf run -m <module>`) is a valid workaround. This might indicate that there's something weird in how `click` (the param parser/cli wrapper) works, but for me workaround works, so all good.

**Comment by nolar** [comment]
That's not Click, that's Python's own importing machinery. #634 fixes this specific case, though I am not sure this is the right way to inject modules from scripts. But should be sufficient for the narrow use-cases of `kopf run ...`.

**Comment by nolar** [comment]
Somewhat related (Python's importing machinery side-effects): https://github.com/nolar/kopf/issues/393#issuecomment-706386845

**Comment by nolar** [comment]
Presumably fixed in #634 and pre-released in `kopf>=1.29.0rc2`.

Can you please try it?

If the issue reappears, please reopen this issue.

**Comment by eshepelyuk** [comment]
@trondhindenes could you plz confirm this is fixed ?
We are also evaluating kopf and want to use pydantic

**Comment by trondhindenes** [comment]
thanks @nolar ! Tested and confirmed @eshepelyuk

**Comment by eshepelyuk** [comment]
Thank you all !
