### ISSUE TITLE
Authentication during startup

### ISSUE THREAD

**Issue by trondhindenes** [nolar/kopf#633]
## Problem
I'm trying to create/update CRDs using the `@kopf.on.startup()` event. However, it seems to me that the authentication even has not yet fired, which means that there is no valid connection to the Kubernetes api.

I can get around this by running `config.load_kube_config()` and/or `config.load_incluster_config()` but it seems a bit dirty (this is what the kopf authentication stuff is mode for, after all).

## Proposal
Add a new event, `@kopf.on.post_auth_startup()` that executes after the authentication stuff is initialized.

## Checklist

- [x] Many users can benefit from this feature, it is not a one-time case
- [x] The proposal is related to the K8s operator framework, not to the K8s client libraries

**Comment by nolar** [comment]
> _this is what the kopf authentication stuff is mode for_

Well, not exactly.

More on that, Kopf does not have its own authentication (almost). It can provide only a rudimentary auth for its own purposes — tokens, username-password, and SSL client certs — by passing them down to the HTTP client library (and barely understanding what are those things for); and it optionally piggybacks either `pykube-ng` or the official `kubernetes` client by asking them to authenticate and then extracting the credentials (but not by using these clients!).

The latter is by itself a hack to make Kopf functioning with some unusual clusters (like GCP/GKE). 

The credentials — either the rudimentary ones or the extracted ones — are not exposed to the handlers/operators/users but only used internally to talk to the API. Kopf is not a K8s API client library, so it does not expose any kind of resource/object manipulation tools either. _(Though I consider it, but it is a different story.)_

Thus, the only proper way to manipulate K8s objects/resources is by using any other client library with its own authentication — even if this happens inside of a handler (either a resource handler or the operator's startup/shutdown handler). I am not sure why this seems dirty — it is fine for me.

PS: For some narrow use-cases, a dict-like `patch` kwarg can be used, but it is limited to the currently handled resource and was actually one of Kopf's internals exposed to the user by accident (but it will stay there). This is the only case where Kopf allows the object/resource manipulation.

**Comment by trondhindenes** [comment]
ah, gotcha. In that case I guess it's not an antipattern to just use `config.load_incluster_config()` to grab a service-account-authenticated session to talk to kubernetes. It wasn't completely clear from the documentation how the authentication hooks in kopf are used, so I just assumed. Maybe there's a potential doc improvement in there.

**Comment by nolar** [comment]
Documentation pull requests are welcome! ;-) 

Regarding the on-login handlers — I now see what was the source of confusion. Right, those are here as a yet another way to "extract" credentials from the sources the framework is not aware of (i.e. neither tokens-passwords-sslcerts, nor `pykube-ng`, nor `kubernetes`). E.g. if you have your own auth system for K8s or an unusual cloud vendor — this is where the on-login handlers can be useful: to retrieve the HTTP-usable credentials "no matter how".

**Comment by trondhindenes** [comment]
docs PRs are often difficult because they require the author to have in-depth knowledge of the subject. Which is why it is often difficult for people asking for doc improvements to actually submit the PR.

But in this case, I guess the "Authentication" section could include something like:

"in most setups, use the normal kubernets client auth(such as `load_incluster_config`) that you would in any app interacting with the Kubernetes api. Custom authentication is only needed if the normal methods for some reason don't work in your setup".

If you want, I'd be happy to make a PR with that addition to the doc text

**Comment by nolar** [comment]
I agree: you are right about the domain/subject knowledge. Thanks for pointing to the specific sections worth improving — I'll take a look.
