### ISSUE TITLE
Patch Deployment

### ISSUE THREAD

**Issue by floriankoch** [nolar/kopf#654]
## Question

How can i update an exsiting Deployment with a new Version. 
I assumed i create a new deployment object with the new values, and the use patch_namespaced_deployment with the new opject as body, but i got 409 Already Exists.

Do i need to manually construct the patch with the diff method (as explained here patch_namespaced_deployment) ,or is there a better way for this?

## Checklist

- [x ] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x ] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords
Update, Patch, Deployment

**Comment by nolar** [comment]
Can you please clarify which `patchNamespacedDeployment` and `patch_namespaced_deployment` do you mean? Kopf does not provide such methods. If you are talking about the Kubernetes client library, it might be better to ask the question in its repo.

Some code snippets and logs would be helpful (if it is related to Kopf).

**Comment by floriankoch** [comment]
@nolar you are right, its a question about the Kubernetes client library
Sorry for the confusion
