### ISSUE TITLE
Replacement for cause.resource.plural?

### ISSUE THREAD

**Issue by nemethf** [nolar/kopf#657]
## Question

Prior to version 1.29, I relied on cause.resource.plural to identify the resource type which an event handler with multiple decorators works on.  Now that cause is removed, how can an event handler access this information?

Unfortunately I cannot find a single place listing all the possible items in a kwargs of an event handler.  And logging kwargs shows nothing interesting.  It seems the resource type can be extracted from meta.selfLink, but I hope there's a more reliable way.

Thanks.

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

cause, resource

**Comment by nolar** [comment]
The single place for all arguments is https://kopf.readthedocs.io/en/stable/kwargs/

But you are right, the resource-related argument is missing. I’ll make it as a hotfix in 1-2 days. Thanks for noticing and reporting.

**Comment by nolar** [comment]
Released as [1.29.1](https://github.com/nolar/kopf/releases/tag/1.29.1). There are two ways now to handle multiple decorators for a single function:

Way 1: using the `resource` kwarg: [doc](https://kopf.readthedocs.io/en/stable/kwargs/#body-parts), [fields & methods](https://kopf.readthedocs.io/en/stable/packages/kopf/#kopf.Resource), PR #658.

Way 2: using the `param` option & kwarg: [doc](https://kopf.readthedocs.io/en/stable/kwargs/#parametrization), PR #659.

**Comment by nolar** [comment]
I assume this issue is fixed now. If not, please reopen with new details.
