### ISSUE TITLE
How to check kubectl delete force flag in delete handler

### ISSUE THREAD

**Issue by sajuptpm** [nolar/kopf#662]
## Question

How can i check **--grace-period 0**  and **--force** flags in **@on.delete** handler ?
what is the recommended way to implement force delete and force check in operator handler ?

**Comment by nolar** [comment]
I'm not sure I've got the question. Kopf does not delete resources. It only reacts to the deletion. Therefore, Kopf has no flags for forced deletion.

If you want that Kopf does not put the finalizer on the resource (thus not blocking it from deletion), then either remove any deletion handlers, or define them with `optional=True` (see the blue note here: https://kopf.readthedocs.io/en/latest/handlers/?highlight=optional#state-changing-handlers). In that case, the handler is not guaranteed to be invoked though.

```python
import kopf

@kopf.on.delete('kopfexamples', optional=True)
def when_deleted(**_): ...
```

**Comment by sajuptpm** [comment]
thanks nolar for quick reply.
I want to show some warning when delete CR request comes and prompt for continue ? Yes/No ? and delete the CR only when user select Yes.
I was thinking about writing admission validation webhook to show the warning and skip the deletion, but how can i tell validation webhook to dont show the warning and continue ?
I think, kopf cant help me to implement this flow ?

**Comment by sajuptpm** [comment]
```
$ curl -k -v -XDELETE  -H "Accept: application/json" -H "Content-Type: application/json"  http://127.0.0.1:8001/api/v1/namespaces/default/pods/security-context-demo --data '{"gracePeriodSeconds":0,"propagationPolicy":"Background"}'
```
do we get **propagationPolicy** or **gracePeriodSeconds** inside the delete handler ?

**Comment by nolar** [comment]
> do we get propagationPolicy or gracePeriodSeconds inside the delete handler ?

Handlers get only what K8s stores on the resources. `gracePeriodSeconds` is mentioned here: https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/object-meta/#Read-only — so it must be available, but only after the object is marked for deletion.

`propagationPolicy` is not mentioned for any structures in [K8s API Reference](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.19/), only for query params. Presumably, it only affect K8s's behaviour internally.

**Comment by nolar** [comment]
I presume, the question is answered, so I can close it. If there are follow-up questions, feel free to reopen this one or create a new question (whatever is more convenient).
