### ISSUE TITLE
[proposal] create helm starter

### ISSUE THREAD

**Issue by eshepelyuk** [nolar/kopf#668]
## Long story short

To make new operator creation easier, I propose to create a helm starter.

https://helm.sh/docs/topics/charts/

## Description

A bootstrapping new operator will be easy as 

```
$ helm create --starter kopf my-py-op
$ cd my-py-op
... build docker ... 
$ helm install my-py-op .
```

The starter will create sample python code structure with sample empty operator entry point.
Also service account and RBAC resources will be generated.

To buuld docker image and run locally during development I propose to leverage skaffold https://skaffold.dev/

@nolar wdyt ? I will contribute if you're interested.

**Comment by nolar** [comment]
@eshepelyuk Integration with various SDKs & dev tools is definitely in the scope, but not planned yet. Specifically, to ease the operators' packaging, delivery, and deployment for operators' developers.

However, I am not that much familiar with Helm (I only know what it conceptually is), so I will take a couple of weeks to read about it and think on how to fit it into a bigger picture before giving any specific answer. I would appreciate a more detailed user story on how it could look like: i.e., what a developer does (step by step), what they get (yaml samples?), where that goes to…

I am not so sure about skaffold though (I am not against it, just uncertain yet). One of Kopf's primary promises is that it is capable of running in the dev machines & IDEs (with breakpoints and other things). Can you please describe a use-case where a tool like Skaffold needed?
