### ISSUE TITLE
Scoping and liveness in embedded mode?

### ISSUE THREAD

**Issue by OmegaVVeapon** [nolar/kopf#684]
## Question

Hi, so I recently refactored some of my code to use [embedding](https://kopf.readthedocs.io/en/stable/embedding/) but now that I don't have access to the `kopf run` CLI flags, I feel a bit like a second-class citizen 😞 

I'm currently trying to find out how to resolve this warning:

> /.venv/lib/python3.8/site-packages/kopf/reactor/running.py:157: FutureWarning: Absence of either namespaces or cluster-wide flag will become an error soon. For now, switching to the cluster-wide mode for backward compatibility.                                                                              > warnings.warn("Absence of either namespaces or cluster-wide flag will become an error soon."

My understanding from checking the docs if that I basically need to do what's documented in [scopes](https://kopf.readthedocs.io/en/stable/scopes/) section but that's all using CLI flags...

I looked around the code and deeper into the docs but the closest thing I found was the [ScanningSettings](https://kopf.readthedocs.io/en/stable/packages/kopf.structs.configuration/#kopf.structs.configuration.ScanningSettings) which seems to be a different thing... so yeah, I don't know how to set specific namespace(s) or cluster-wide without the flags.

The other issue I'm having is setting the liveness probes which are also only [documented](https://kopf.readthedocs.io/en/stable/probing/?highlight=liveness#liveness-endpoints) via CLI flags.

I can probably survive without the liveness but the namespaces are ~critical~ more important... what can I do here?

P.S. Using the latest kopf 1.29.2

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

- liveness
- namespaces
- cluster-wide
- OperatorSettings

**Comment by nolar** [comment]
Sorry, the embedded operators' parameters are indeed not well-documented. That can be improved.

Most likely, you call either `run()` or `operator()`. They both accept a bunch of parameters: https://github.com/nolar/kopf/blob/1.29.2/kopf/reactor/running.py#L72-L87

For the cluster-wide/namespaced mode, you need either `namespaces=['default']` or `clusterwide=True`.

For a liveness probe, that is `liveness_endpoint="http://0.0.0.0:1234"`.

All other CLI args except for logging/verbosity are [just passed](https://github.com/nolar/kopf/blob/1.29.2/kopf/cli.py#L98-L103) to this function's arguments "as is". 

For logging, you have to configure loggers/handlers/formatters/levels yourselves (usually, app-specific), or use a macro [`kopf.configure()`](https://github.com/nolar/kopf/blob/1.29.2/kopf/engines/loggers.py#L200-L207) — but that might affect your app's loggers.

**Comment by OmegaVVeapon** [comment]
Thanks again @nolar.

Everything worked as advertised! I'm back to having everything I had with `kopf run` with the embedded operator 🎉 

Question answered, closing ticket.
