### ISSUE TITLE
Regression in kopf.adopt() in 1.30.

### ISSUE THREAD

**Issue by GrahamDumpleton** [nolar/kopf#725]
## Long story short

The ``kopf.adopt()`` function now only appears to work where parent and child resources are both namespaced. This is not the only combination that is possible, and so code that previous relied on other possibilities now fails.

## Description

For owner references, it is believed the following working combinations work.

* Parent is namespaced, child is namespaced.
* Parent is cluster scoped (non namespaced), child is cluster scoped.
* Parent is cluster scoped, child is namespaced.

Note that the following are believed not to be possible.

* Parent is namespaced, child is namespaced but child is in a different namespace to the parent.
* Parent is namespaced, child is cluster scoped.

Prior to 1.30, all three of the above working combinations were supported. In 1.30, only the first now works.

If you attempt to have the others, you trigger the check:

* https://github.com/nolar/kopf/blob/e71dc607f31ccd0697895e83c3b795c3f685b3d2/kopf/toolkits/hierarchies.py#L204

and get an exception saying that parent needs to be namespaced.

## Environment

* Kopf version: 1.30.2
* Kubernetes version: 1.19
* Python version: 3.7
* OS/platform: Fedora

**Comment by nolar** [comment]
Thank you for noticing and reporting this!

A hotfix from #726 is released in 1.30.3 & 1.31rc2.

**Comment by nolar** [comment]
If the issue reappears, please reopen.
