### ISSUE TITLE
Use memos/indices in global handlers

### ISSUE THREAD

**Issue by psontag** [nolar/kopf#735]
## Problem

I would like to use the `kopf.Memo` and `kopf.Index` features inside a global handler function that is not specific to any Kubernetes resource. In my use case this global handler would run an expensive computation based on the provided `kopf.Index` and save the result in the `kopf.Memo`. This result could then be used inside other resource specific handlers.

Example:
```python
import kopf

@kopf.index("pods")
def all_pods(**_):
    ...

# A global daemon or timer that is not specific to a Kubernetes resource
# but has access to the memos and indices of kopf
@kopf.daemon()
def global_handler(all_pods: kopf.Index, memo: kopf.Memo, **_):
    # some computation with the index
    memo.result = computation_result

@kopf.timer("KopfExample", intervall=30)
def example_handler(memo: kopf.Memo, **_):
    # do something with memo.result and the KopfExample resource
```

In the [docs](https://kopf.readthedocs.io/en/stable/memos/#operator-memos) there is an example on how you can use `kopf.Memo` in different threads with the help of a `Queue`, but I think there is currently no way to access a `kopf.Index` from other threads?

## Proposal

One solution for this might be to not require a Kubernetes resource when creating a `kopf.timer()` or `kopf.daemon()`. Of course most of the `kwargs` provided by kopf do not make sense in the case no specific resource is watched. So a better solution might be to introduce a new type for global handlers.

```python
import kopf

@kopf.daemon()
def global_handler1(my_index: kopf.Index, memo: kopf.Memo, **_):
    ...

@kopf.timer(interval=30.0)
def global_handler2(my_index: kopf.Index, memo: kopf.Memo, **_):
    ...
```

## Checklist

- [x] Many users can benefit from this feature, it is not a one-time case
- [x] The proposal is related to the K8s operator framework, not to the K8s client libraries

**Comment by nolar** [comment]
Hello. I see two questions here, I'll answer them both.

Regarding _"there is currently no way to access a kopf.Index from other threads"_ — can you please clarify what do you mean? 

The indices are [officially documented as guaranteed](https://kopf.readthedocs.io/en/stable/indexing/#guarantees) to be passed to all handlers, including startup handlers (though they will be empty or partially populated at that time). As such, you can pass the index instances to the threads, and access them from the threads — the same as the queue in the mentioned example. 

Do you have problems with this usage pattern? If so, some details would be helpful about the issue, as this would be a violation of promises, i.e. a bug worth fixing.

---

The per-operator "system" daemons/timers are the idea I often have myself. However, I do not see how it is different from having a self-made thread/task started from the startup handler (which takes only 1-2 extra lines of code), and whether the Kubernetes operator framework should provide general-purpose non-Kubernetes-specialised threading/multitasking toolkits.

**Comment by psontag** [comment]
Sorry for the long delay here and thank you for your answer.

> The indices are officially documented as guaranteed to be passed to all handlers, including startup handlers (though they will be empty or partially populated at that time). As such, you can pass the index instances to the threads, and access them from the threads — the same as the queue in the mentioned example.

Thanks for clarifying this. I must have totally missed that.

> The per-operator "system" daemons/timers are the idea I often have myself. However, I do not see how it is different from having a self-made thread/task started from the startup handler (which takes only 1-2 extra lines of code), and whether the Kubernetes operator framework should provide general-purpose non-Kubernetes-specialised threading/multitasking toolkits.

I think it would just be a convenience feature for the developer. I agree with you that this probably does not really fit with the Kopf framework at the moment.
