### ISSUE TITLE
Serial/Ordered Object Creation

### ISSUE THREAD

**Issue by infinitydon** [nolar/kopf#739]
## Question

Is it possible to use kopf directly to create k8s objects in a desired order, for example:

- Create configmap first 
- Make sure confgimap was created then proceed to create Database Deployment.
- Make sure Database Deployment is in the running status
- Create Web Deployment

Above is just an example whereby some objects needs other objects to be running before they are initialized.

Is this something that is inbuilt with kopf or needs to be implemented using k8s clients like pykube-ng?

Any other reference/examples will be appreciated.

Kudo has this kind of [functionality ](https://kudo.dev/docs/developing-operators/plans.html#overview) but I will like to implement this using kopf.

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

serial deployment
ordered
phase

**Comment by nolar** [comment]
The short answer is: sorry, but no, Kopf cannot create objects. 

In general, Kopf is not a Kubernetes client library, it is a framework for Kubernetes operators. More on that, Kopf tries to be client-agnostic and supports any client libraries which developers prefer to use. Pykube[-ng] is one of them — just my personal preference, there are no requirements to use this one specifically (besides, it has its flaws: e.g., it is synchronous).

Easy creation of hierarchies of cascaded children objects natively in Kopf is something on the table and under consideration, but not yet implemented, not yet drafted, not even planned for the nearest future. It might be considered as far-future ~plans~ wishes.

As a side note, I would like to say, that if there are such terms as "flow", "workflow", "steps", "phases", "stages", "dependencies" in play, it is worth taking a look at specialised workflow engines or operators. We use [Argo](https://argoproj.github.io/argo-workflows/)+Kopf for our needs. Kudo seems like an option too, but I never tried it. You can even make your own engine/operator on top of Kopf which would support declarative workflows with steps and dependencies. 

From my experience, I can even state that Kopf nicely integrates with such tools — as long as they "communicate" via custom resources: the workflows can be orchestrated by Argo/Kudo/etc, which should create custom resources for the low-level app-specific arbitrary-logic parts, which in turn can be implemented with Kopf (this is what we do).

Sadly, I have no enough personal time to implement or even maintain this quite big functionality (I mean, workflows). Though, I would be happy to advertise such a tool if it is made on top of Kopf ;-)

Hopefully, I could address your question(s) properly.

**Comment by infinitydon** [comment]
Thanks Nolar for the prompt response and suggestion.. The combination of Argo + kopf seems okay, I will give it a try.
