### ISSUE TITLE
sometimes I need a transparent handler to watch resource change without patch result or status back.

### ISSUE THREAD

**Issue by ktlcove** [nolar/kopf#781]
## Problem

 In current state, if I want to use kopf to watch resource change and do sth. I have to grant patch permisison to the serviceaccount of kopf pod. 
but in some case it is not necessary to path process status or result back, cause I don't care about or need it.

so I add a parameter ```configuration.progress_storage.disabled``` to disable patch resource. (kopf verison 1.30.0)

```diff
diff --git a/kopf/reactor/effects.py b/kopf/reactor/effects.py
index bbc4389..4f9812e 100644
--- a/kopf/reactor/effects.py
+++ b/kopf/reactor/effects.py
@@ -58,7 +58,8 @@ async def apply(
         settings.persistence.progress_storage.touch(body=body, patch=patch, value=None)
 
     # Actually patch if it was not empty originally or after the dummies removal.
-    await patch_and_check(resource=resource, patch=patch, body=body, logger=logger)
+    await patch_and_check(resource=resource, patch=patch, body=body, logger=logger,
+                          ignore=settings.persistence.disabled)
 
     # Sleep strictly after patching, never before -- to keep the status proper.
     # The patching above, if done, interrupts the sleep instantly, so we skip it at all.
@@ -87,7 +88,8 @@ async def apply(
             value = datetime.datetime.utcnow().isoformat()
             touch = patches.Patch()
             settings.persistence.progress_storage.touch(body=body, patch=touch, value=value)
-            await patch_and_check(resource=resource, patch=touch, body=body, logger=logger)
+            await patch_and_check(resource=resource, patch=touch, body=body, logger=logger,
+                                  ignore=settings.persistence.disabled)
     elif not patch:  # no patch/touch and no delay
         applied = True
     return applied
@@ -99,6 +101,7 @@ async def patch_and_check(
         body: bodies.Body,
         patch: patches.Patch,
         logger: Union[logging.Logger, logging.LoggerAdapter],
+        ignore: bool = False,
 ) -> None:
     """
     Apply a patch and verify that it is applied correctly.
@@ -114,7 +117,7 @@ async def patch_and_check(
     For normal fields (e.g. in spec/status), an empty list/dict is still
     a value and is persisted in the object and matches with the patch.
     """
-    if patch:
+    if not ignore and patch:
         logger.debug(f"Patching with: {patch!r}")
         resulting_body = await patching.patch_obj(
             resource=resource,
diff --git a/kopf/structs/configuration.py b/kopf/structs/configuration.py
index 6329a6f..479833f 100644
--- a/kopf/structs/configuration.py
+++ b/kopf/structs/configuration.py
@@ -316,6 +316,10 @@ class PersistenceSettings:
     """
     How the resource's essence (non-technical, contentful fields) are stored.
     """
+    disabled = False
 
 
 @dataclasses.dataclass
```

but when I set ```configuration.progress_storage.disabled = True```  kopf can't patch anything to resource.

so I think kopf may need a feature like this

```python
# if set transparent_process to True, kopf will not patch anything just trigger fn on resource update
@kopf.on.update('kopfsample', transparent_process=True)
async def fn(**_):
    pass
```
 
but when I try to do this feature by myself , I found there're lots of stage put anything they want to patch to resource to the patch, and finally kopf commit this patch .  It's hard for me.

So now , I have to start two kopf instance individually
kopf A  set  ```configuration.progress_storage.disabled = True```  and handle those resource which no need to patch anything back.
kopf B works as usual and handle other resource which need to patch process status or result back to origin resource.
It works, but not graceful. So I open this feature here with my confuse English. ^_^
Wish kopf more and more useful.

## Checklist

- [x] Many users can benefit from this feature, it is not a one-time case
- [ ] The proposal is related to the K8s operator framework, not to the K8s client libraries

**Comment by nolar** [comment]
Hello @ktlcove! Thanks for posting this question and for using Kopf. Your English is fine, don't worry!

On-update/on-creation/on-deletion handlers are intended to be stateful, as they react to state changes. With no state stored, they become essentially useless.

Did you consider using the low-level `@kopf.on.event()`? It is intended to be stateless and as simple as possible. Specifically, it stores no state on resources (unless there are stateful handlers for the same resource; and unless the function explicitly returns something).

It seems like this is exactly what you are looking for. If not, can you please explain what is missing or what is wrong with event handlers?

* https://kopf.readthedocs.io/en/stable/handlers/#event-watching-handlers

**Comment by ktlcove** [comment]
> Hello @ktlcove! Thanks for posting this question and for using Kopf. Your English is fine, don't worry!
> 
> On-update/on-creation/on-deletion handlers are intended to be stateful, as they react to state changes. With no state stored, they become essentially useless.
> 
> Did you consider using the low-level `@kopf.on.event()`? It is intended to be stateless and as simple as possible. Specifically, it stores no state on resources (unless there are stateful handlers for the same resource; and unless the function explicitly returns something).
> 
> It seems like this is exactly what you are looking for. If not, can you please explain what is missing or what is wrong with event handlers?
> 
> * https://kopf.readthedocs.io/en/stable/handlers/#event-watching-handlers

I watch the document again ,  I'm sure ```@kopf.on.event()``` is what I want.
Thanks @nolar
