### ISSUE TITLE
In memory cache share for a Kind (not resource)

### ISSUE THREAD

**Issue by smileisak** [nolar/kopf#799]
## Question

Is there any way to store data in memory for a specific Kind (not resource) and access this data within handlers for all resources ?

I want to store JWT tokens and reuse them in all resources related to the Kind.

## Checklist

- [x] I have read the [documentation](https://kopf.readthedocs.io/en/latest/) and searched there for the problem
- [x] I have searched in the [GitHub Issues](https://github.com/nolar/kopf/issues?utf8=%E2%9C%93&q=) for similar questions

## Keywords

`memory` `cache`

**Comment by psontag** [comment]
You should be able to do this with [Operator Memos](https://kopf.readthedocs.io/en/stable/memos/#operator-memos). You can create a `memo` in your startup handler and store the JWT token in that memo. Operator memos are available in all handlers, independent of the resource kind.

**Comment by smileisak** [comment]
Thank you @philipp-sontag-by for your response, exactly it is possible to make it with operator's memo.

I'll close this issue to have the 100 issue :)

**Comment by smileisak** [comment]
I want to reopen this discussion.

Documentation says


___Any changes to the operator’s container since the first appearance of the resource are not replicated to the existing resources’ containers, and are not guaranteed to be seen by the new resources (even if they are now).___

I've tested and when the JWT generated in the operator's startup handler expires, it cannot be reset again in the resource and shared with other resources.

**Comment by psontag** [comment]
How are you currently using the memo?
The documentation says
> However, due to shallow copying, the mutable objects (lists, dicts, and even custom instances of kopf.Memo itself) in the operator’s container can be modified from outside, and these changes will be seen in all individual resource handlers & daemons which use their per-resource containers.

So if you store your token in a dictionary like this

```Python 
@kopf.on.startup()
def start_background_worker(memo: kopf.Memo, **_):
    memo.jwt_token= {"token": "your token"}
```
You should be able to refresh it inside your resource handler.

**Comment by smileisak** [comment]
Exactly ! Thanks again. I did not think that we can create arbitrary attributes like `memo.jwt_token`.
