### ISSUE TITLE
thirdparty support for kubernetes_asyncio?

### ISSUE THREAD

**Issue by caffeinism** [nolar/kopf#806]
### Problem

I am using the kubernetes_asyncio library to asynchronously call to Kubernetes APIs.

However, kopf.adopt(naturally harmonize_naming, adjust_namespace and label too) supports kubernetes.client.model but not kubernetes_asyncio.client.model.

https://github.com/nolar/kopf/blob/aee09c87d39dfb99a715783523bd20f4d30bc9b9/kopf/_cogs/helpers/thirdparty.py#L36

Since kubernetes_asyncio follows the model of the kubernetes python sdk as it is, there is no problem with compatibility.

### Proposal

I wish this project also supports kubernetes_asyncio.

### Code

```
if any(C.__module__.startswith('kubernetes.client.models.') for C in subcls.__mro__): 
    return True
```
It would be nice to change that part to
```
if any(C.__module__.startswith('kubernetes.client.models.') for C in subcls.__mro__): 
    return True
if any(C.__module__.startswith('kubernetes_asyncio.client.models.') for C in subcls.__mro__): 
    return True
```

**Comment by nolar** [comment]
Hello. I agree this will be better. Would you like to send a pull request? If so, please also update `docs/hierarchies.rst` to mention this change — the very top and the very bottom of the file (at least the links, no need for code snippets, I guess).

**Comment by m3talstorm** [comment]
We also need this feature
