### ISSUE TITLE
Removing the ":linenos:" from the ".. code-block:: python" in the .py files to improve readability and make it easy to copy

### ISSUE THREAD

**Issue by tavaresrodrigo** [nolar/kopf#807]
### Keywords

linenos, code-block, line numbers

### Problem

When we cc code samples with line numbers from the documentation, as we can see from the snippet below, we end up having to remove the numbers in the code editor which naturally displays line numbers for all files. 

``` python
 1import os
 2import kopf
 3import kubernetes
 4import yaml
 5
 6@kopf.on.create('ephemeralvolumeclaims')
 7def create_fn(spec, name, namespace, logger, **kwargs):
 8
 9    size = spec.get('size')
[...]
```

Wouldn't be better to remove the :linenos: so we can copy and past python files from documentation without the need to remove the line numbers as below? 

```python
import os
import kopf
import kubernetes
import yaml

@kopf.on.create('ephemeralvolumeclaims')
def create_fn(spec, name, namespace, logger, **kwargs):

    size = spec.get('size')
```

I know is a minor change but having to manually remove the line numbers can be very annoying for less experienced programmers or anyone else willing to test kopf, I believe that by removing the line numbers we would be following the same standard being applied to the yaml and bash files already in the documentation and also improve the code readability.

**Comment by nolar** [comment]
Solved in #808
