### ISSUE TITLE
KOPF Requesting RBAC Permissions for Mutating Webhook Resource

### ISSUE THREAD

**Issue by cjbaar** [nolar/kopf#816]
### Keywords

rbac mutate

### Problem

I have added a MutatingWebhook to our kopf operator. The definition is as follows:
```
@k8s.kopf.on.mutate(
    'deployment',
    when=filter_by_security_plane,
    param='mutate_deployment'
)
```

On startup, the operator is complaining that is does not have RBAC permissions to watch deployments.
```
[2021-08-10 14:16:03,271] kopf._core.reactor.o [ERROR   ] Watcher for deployments.v1.apps@none has failed: ('deployments.apps is forbidden: User "xxx" cannot list resource "deployments" in API group "apps" at the cluster scope', {'kind': 'Status', 'apiVersion': 'v1', 'metadata': {}, 'status': 'Failure', 'message': 'deployments.apps is forbidden: User "xxx" cannot list resource "deployments" in API group "apps" at the cluster scope', 'reason': 'Forbidden', 'details': {'group': 'apps', 'kind': 'deployments'}, 'code': 403})
```

I did not add these permissions to the Role or ClusterRole, because it is running as webhook, not a watch handler. Why does kopf attempt to start a watcher for this? I should not have to grant permissions to the operator, since these requests only come in via the webhook API, correct?

**Comment by nolar** [comment]
Right! You are correct. This is indeed a bug: Kopf tries to watch all known resource kinds, even some of them have no regular handlers requiring the watch-streams — a legacy assumption from the time when only regular handlers existed, webhooks were absent. Thanks for reporting. 

I think it will be easy to fix. Actually, looking at the code (introduced in #708), this line should not be there: https://github.com/nolar/kopf/blob/1.33.0/kopf/_core/reactor/observation.py#L218. And maybe another similar line in the same module. But it is better to check if removing it does not break other things.

**Comment by nolar** [comment]
Re-open: it seems, the solution in #826 (reverted in #830) excludes the admission-only resources not only from watching but also from being included in the managed webhook configurations — so that such resources are not served even for admission.
