### ISSUE TITLE
Ability to handle subresources changes in the addmission webhooks

### ISSUE THREAD

**Issue by SergeyTsaplin** [nolar/kopf#825]
### Problem

I want to be able to handle subresources changes in the admission webhooks, for example when a `status` subresource of a CRD has been changed

### Additional information

Note:

https://github.com/nolar/kopf/blob/1.33.0/kopf/_core/engines/admission.py#L409

```py
[f’{resource.plural}/*’]
```

**Comment by nolar** [comment]
Pre-released as `kopf==1.34rc1` ([link](https://github.com/nolar/kopf/releases/tag/1.34rc1)) — can you please check that it works? See #832 for the syntax (also in the docs & examples).
