### ISSUE TITLE
Common patterns and best practices

### ISSUE THREAD

**Issue by thismatters** [nolar/kopf#876]
### Keywords

patterns, best practices, multistep processes

### Problem

I'm very new to kubernetes operators, so please forgive my ignorance. I've spent a little time looking at projects using `kopf` and haven't had much success finding a pattern that suits my use case; also I've spent some time looking for a community centered around `kopf` and have come up empty. Is there a discord server or a subreddit or something for connecting newbies like me with a more experienced user?

I'm working on an operator which will coordinate a multistep deployment process and I'm wondering if there are best practices when doing this. I'll layout the essentials:
* Start Pod A which will run permanently
* Once Pod A is running and reachable start Pod B to run several commands and die
* Once Pod B is done start Pod C

It seems possible to do this with one monolithic handler:
```py
@kopf.on.create("my", "v1", "crd")
def create(**kwargs):
  # create pod A
  await pod_a_started()  # I'm not positive how to make this determination
  # create pod B
  await pod_b_finished()  # also not positive how to make this determination
  # create pod C
  return {"started": True}
```

It also seems possible to have event handlers for each step in the process:
```py 
@kopf.on.create("my", "v1", "crd")
def begin_init(**kwargs):
  # create pod A
  return {"initializing": True}

@kopf.on.event(annotations="pod_a_annotations")
def continue_init(**kwargs):
  # ensure state is right for continuation
  # create pod B
  return {"migrating": True}

@kopf.on.event(annotations="pod_b_annotations")
def create(**kwargs):
  # ensure state is right for continuation
  # create pod C
  return {"started": True}
```

Which pattern would be considered best practice? 

Aside from that, in the first pattern is there a good way to assess whether pod B (for example) has completed execution?

Finally, is there a better place to pose these kinds of questions?

**Comment by thismatters** [comment]
I've been working through my uncertainty and have [a working concept now](https://github.com/thismatters/django-operator). I went with the monolithic approach for now and figured out how to query the k8s api using the `kubernetes` python library to get the status for a pod. 

Now that I have it roughly working I'm rethinking the monolithic approach. The drawback I've seen is that the `patch` updates and events aren't pushed until the handlers are complete (seemingly this is also the case for sub-handlers). It would be best for the changes to status to be more immediate, and I think that smaller handlers which act in sequence would achieve that goal. I'm still not fully clear if the pattern I suggested above (using event handlers) would work; I think that the "no events on events" restriction might prove troublesome there. Another alternative is to have several `create`/`update` handlers that just wait until their turn comes up; although this seems like there is a lot of potential for trouble there.

I'm also thinking about creating an intermediate resource that could track the state of the main resource and coordinate actions.

**Comment by nolar** [comment]
Hello. Thanks for asking these questions, and sorry for the delay.

First, for the technical question. The on-creation/update/deletion/resuming handlers are supposed to be instant or at least fast (i.e. seconds). They are not designed to run for a long time (minutes or hours). Trying to do so will lead to a plethora of fancy side-effects and instability.

Depending on your familiarity with event-driven development, you might want to go with the second approach with separate handlers or sub-handlers. I usually prefer that way, using a set of labels/annotations and filtering by them (using Kopf's [filters](https://kopf.readthedocs.io/en/stable/filters/)) — to select to what and when to react. In some cases, these labels (usually, one label) can make a little state machine.

Or, if you do not like event-driven systems, you can take a look at Kopf [daemons](https://kopf.readthedocs.io/en/stable/daemons/) — they are designed to run for prolonged times and do something in the background, e.g. wait for pods. Some care should be taken to skip (step over) the already executed sections on operator restarts, as daemons are also restarted.

There is no established pattern for this, it all depends on the task and your preferences.

For your case, you might also want to consider using the more specialised workflow operators/engines, such as [Argo Workflows](https://argoproj.github.io/workflows/).

---

As for the second question about the community: I am not sure there is one — I did not try to build it (yet). 

I personally try to help from time to time here in GitHub — e.g. in Kopf's [discussions](https://github.com/nolar/kopf/discussions) and [issues](https://github.com/nolar/kopf/issues). However, I do not have much time and energy for this, so I do it mostly on weekends (not every weekend). You can sometimes get answers from others, but I'm not sure if anyone else is monitoring this actively (or subscribed to it).

There is a community of operator developers in the Kubernetes official Slack (linked below). They are about operators in general, not Kopf-based specifically, mostly Go-based — but Kopf is sometimes mentioned there as I saw some discussions, and I personally try to help from time to time, but others can help with the general operator design (it is language agnostic, basically).

* Login: https://kubernetes.slack.com/
* Self-invite: https://slack.k8s.io/ or http://slack.kubernetes.io/
* `#kubernetes-operators` channel: https://app.slack.com/client/T09NY5SBT/CAW0GV7A5

I am not aware of any other communities but would be happy to join them — if you can find anything.

**Comment by thismatters** [comment]
Thank you for your time on this. The package works great!

I'm scaffolding an event driven flow, but I'm running into problems using `patch` to update the labels:

```py
@kopf.on.update("thismatters.github", "v1alpha", "djangos", labels={"migration-state": "red"})
def to_green(patch, **kwargs):
    patch.meta["labels"]["migration-state"] = "green"


@kopf.on.update("thismatters.github", "v1alpha", "djangos", labels={"migration-state": "green"})
def to_blue(patch, **kwargs):
    patch.meta["labels"]["migration-state"] = "blue"
```

When I deploy the above I get an exception like this:

```
[2021-12-26 23:52:37,416] kopf.objects         [ERROR   ] [testbed/money-positive] Handler 'to_green' failed with an exception. Will retry.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 283, in execute_handler_once
    result = await invoke_handler(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/execution.py", line 378, in invoke_handler
    result = await invocation.invoke(
  File "/usr/local/lib/python3.9/site-packages/kopf/_core/actions/invocation.py", line 140, in invoke
    await asyncio.shield(future)  # slightly expensive: creates tasks
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "main.py", line 26, in to_green
    patch.meta["labels"]["migration-state"] = "green"
  File "/usr/local/lib/python3.9/site-packages/kopf/_cogs/structs/dicts.py", line 297, in __getitem__
    return resolve(self._src, self._path + (item,))
  File "/usr/local/lib/python3.9/site-packages/kopf/_cogs/structs/dicts.py", line 121, in resolve
    result = result[key]
KeyError: 'metadata'
```

Am I misusing `patch`? The docs imply that I should be able to use it to update `metadata`.

**Comment by thismatters** [comment]
figured that one out. I was misusing `patch`. Correct usage looks like:

```py
@kopf.on.update("thismatters.github", "v1alpha", "djangos", labels={"migration-state": "red"})
def to_green(patch, **kwargs):
    patch.meta.labels["migration-state"] = "green"
```

**Comment by thismatters** [comment]
I've refactored to an event driven "hopscotch" model which is triggered by changes to a particular label. However, I've become a little worried about the corner case where an external update to the object is pushed while the operator is processing another external update; in such a case the newer config would be sent to the handlers for the latter steps which results in an irregular migration. My immediate solution to this is to duplicate the starting `spec` into `status` for all the handlers in the process to reference, and then a final handler confirms that the `spec` still matches what was duplicated into `status`; if the `spec` doesn't match (indicating that a new config was pushed during the migration) then the migration process is restarted with the new `spec`.

The process is book-ended by a start handler which filters the events to ignore irrelevant label changes and stores the intended `spec`; the other end is the finish handler which either restarts the process or cleans up/finalizes the process. The inner handlers all use the `kopf.TemporaryError` to wait for the prior step to complete:

```py
@kopf.on.update("my", "v1", "crd", labels={"migration-step": "red"})
def to_green(patch, retry, **kwargs):
    if retry > 20:
         raise kopf.PermanentError("Took too long...")
    red_status =  # get this from kubernetes
    if red_status != "ready":
        raise kopf.TemporaryError("Not ready yet, waiting", delay=6) 
    # start green thing
    patch.meta.labels["migration-step"] = "green"
```

The handlers now run essentially instantaneously although they may repeat several times before they are completely effective. 

I'm relatively happy with this solution, but I'm open to criticism. I've looked in to daemons but I don't think they fit this use case; my first solution perhaps could have worked as a daemon, but it would have suffered the same potential for mid-migration state drift.

**Comment by thismatters** [comment]
Thanks for the discussion here, and thanks for the ongoing effort of maintaining this project. I have a working operator now and am feeling pretty happy with its functionality. I'm closing this and will shunt any future discussions to the aptly named discussion section.
