### ISSUE TITLE
Warning - Not enough permissions to watch for resources

### ISSUE THREAD

**Issue by vikas027** [nolar/kopf#901]
### Keywords

Not enough permissions to watch for resources

### Problem

My `kopf` operator is working perfectly fine but I am seeing this warning on startup. My service account has limited privileges for obvious reasons. 

Is there a way to silence this warning?

```
[2022-03-07 01:17:39,818] kopf._core.reactor.o [WARNING ] Not enough permissions to watch for resources: changes (creation/deletion/updates) will not be noticed; the resources are only refreshed on operator restarts
```

**Comment by mledoze** [comment]
Hi, the warning comes from here https://github.com/nolar/kopf/blob/06d00944be947bf63a56b10fd4fdc3269d48feb5/kopf/_core/reactor/observation.py#L75

As explained here https://github.com/nolar/kopf/blob/129fe4ced27e097ff92cde6d1b2405e726e4c820/kopf/_cogs/configs/configuration.py#L233

> the operator will try to observe
    the namespaces and custom resources, and will gracefully start/stop
    the watch streams for them (also the peering activities, if applicable).
    This requires RBAC permissions to list/watch the V1 namespaces and CRDs.

If you want to keep the default behavior, you need to grant the operator the required the permissions (list and watch on `customresourcedefinitions` and `namespaces`), see https://kopf.readthedocs.io/en/stable/deployment/#rbac.

Or you can disable the scanning (and silence the warning) at startup:

```python
import kopf 

@kopf.on.startup()
async def on_startup(settings: kopf.OperatorSettings, **_):
    # disable the scanning of custom resources on the cluster
    settings.scanning.disabled = True
```

**Comment by vikas027** [comment]
Thanks, @mledoze  - My operator is working without any warnings now :)
