### ISSUE TITLE
How to silence the healthcheck endpoints in the logs?

### ISSUE THREAD

**Issue by vikas027** [nolar/kopf#902]
### Problem

I have enabled `healthcheck` endpoint `/healthz` on my operator deployment which populates logs in container `STDOUT`

```
[2022-03-07 06:46:19,716] aiohttp.access       [INFO    ] 10.X.X.X [07/Mar/2022:06:46:19 +0000] "GET /healthz HTTP/1.1" 200 177 "-" "kube-probe/1.21+"
```

Is there a way to not have these in the logs?

**Comment by psontag** [comment]
You should be able to get the logger of the aiohttp library and change its log level. Something like this:

ˋˋˋpython
import logging

logging.getLogger('aiohttp.access').setLevel(logging.ERROR)
ˋˋˋ

**Comment by vikas027** [comment]
Thanks, @philipp-sontag-by. That did the trick.
