### ISSUE TITLE
Can adopt be used for objected created in a different namespace their owner?

### ISSUE THREAD

**Issue by Lawouach** [nolar/kopf#903]
### Keywords

adopt

### Problem

I have a controller which lives in a namespace and created objects in a different namespace. I would like to make sure that these objects get automatically deleted when the owner is removed too. But as the owner and its children live in different namespaces, it seems this doesn't work?

Is this a limitation in kopf or a misunderstanding on my part of ownership?

**Comment by mledoze** [comment]
The owner and the child must live in the same namespace. Kopf adds an `ownerReferences` on the child object and must reference an owner that exists on the same namespace.

See here https://kubernetes.io/docs/concepts/overview/working-with-objects/owners-dependents/ for more information.

> A valid owner reference consists of the object name and a UID within the same namespace as the dependent object.

**Comment by Lawouach** [comment]
Oh brilliant. Thank you so much for teaching me a valuable bit here :)

Cheers
