### ISSUE TITLE
kopf doesn't construct JSONPatches correctly when keys include characters like `~` and `/`

### ISSUE THREAD

**Issue by sambhav** [nolar/kopf#918]
This causes issues when trying to patch labels that contain `/` for eg `app.kubernetes.io/created-by`

See the offending lines at

https://github.com/nolar/kopf/blob/ab53ace82e62a6fa709bf5a580007eac1273ac34/kopf/_cogs/structs/patches.py#L94-L101

We need to ensure that `~` is encoded to `~0` and `/` to `~1`

See https://datatracker.ietf.org/doc/html/rfc6901#section-3 and https://github.com/json-patch/json-patch-tests/issues/42

**Comment by savemuri** [comment]
Observed same issue, has anyone figured a workaround?
