### ISSUE TITLE
How to disable "Timer xxx succeeded." events and log messages?

### ISSUE THREAD

**Issue by MartinEmrich** [nolar/kopf#924]
### Keywords

logging events Timer succeeded.

### Problem

For each invoked timer/resource pair, kopf 1.35 both logs a level INFO message and emits a Kubernetes Event like `Timer 'xxx' succeeded.`.

As my controller handles dozens of resources, and the timer runs every two minutes, this clutters both the logs and the kubernetes Events system.

How can I disable these messages? (Sometimes i do log messages with INFO level, so changing the log level to WARNING would not be a good solution).

Thanks!

**Comment by nolar** [comment]
The k8s events can be disabled for the whole operator by setting `settings.posting.level = logging.ERROR` or `settings.posting.enabled = False`:

* https://kopf.readthedocs.io/en/stable/configuration/#logging-events

The timer logs/events cannot be disabled individually.

I can suggest 2 ways to solve the problem:

**The 1st way:** Make an on-startup handler which configures logging — and tweak it to prohibit certain messages. Something like this:

```python
import kopf
import logging

def is_it_not_a_timer(record: logging.LogRecord) -> bool:
    txt = record.getMessage()
    return not txt.startswith("Timer 'xxx'")

@kopf.on.startup()
def hide_timers_logs(**_):
    objlogger = logging.getLogger('kopf.objects')
    objlogger.addFilter(is_it_not_a_timer)
```

Or you can make it a DEBUG level:

```python
def is_it_not_a_timer(record: logging.LogRecord) -> bool:
    txt = record.getMessage()
    if txt.startswith("Timer 'xxx'"):
        record.levelno = logging.DEBUG
        record.levelname = logging.getLevelName(logging.DEBUG)
    return True
```

_(UPD: It was originally modifying the unexistent field `record.level` — fixed for correctness later, see comments below.)_


See more: 

* https://docs.python.org/3/library/logging.html#filter-objects
* https://docs.python.org/3/library/logging.html#logrecord-objects

Please let me know if it works — I didn't test it, just gave some ideas where to look to.

**The 2nd way:** Convert the timer to a daemon with `time.sleep(2)` or `await asyncio.sleep(2)` inside a `while not stopped:` cycle. This is essentially the same as what timers do, with some extra safety measures for faster termination (time.sleep is non-terminable until the sleep ends) and the result preservation features.

**Comment by MartinEmrich** [comment]
@nolar thanks! 

````
settings.posting.level = logging.WARNING
````

worked for me, if I want explicit events in the future, I might follow the documented advice and send them using a K8s API client.

**Comment by jkupferer** [comment]
@nolar Thanks for this. I found the first approach you suggested worked but changing the record level to `logging.DEBUG` did not work for me.

**Comment by nolar** [comment]
I am glad to see that it helped. 

Regarding the logging level trick — my mistake (I did not test it). The proper fields are these:

```python
    if txt.startswith("Timer "):
        record.levelno = logging.DEBUG
        record.levelname = logging.getLevelName(logging.DEBUG)
```

I have fixed my response above if someone comes later looking for this same question.

I consider this question is answered. If you have any other questions, feel free to open a new issue.
