### ISSUE TITLE
Operator logging INFO for every REST call made

### ISSUE THREAD

**Issue by javiermarasco** [nolar/kopf#948]
### Keywords

logging 

### Problem

I made a simple operator that runs a few calls to Azure to query for information on resources deployed there, for every call the code makes to Azure I get an [INFO] log in the logs of the pod where my operator is running, this causes a lot of logging which I don't want to see (90% of them are just the REST call to azure returning a 200).

I tried setting the cli to use warning logging but I get the same result (lots of INFO in the pods log)
`CMD [ "kopf", "run" , "-v", "--log-format=plain", "--liveness=http://0.0.0.0:8080/healthz", "main.py", "-n", "demo"] `

I tried with settings.posting.level = logging.WARNING as well, but the result is the same.

```
@kopf.on.startup() 
def configure(settings: kopf.OperatorSettings, **_): 
    settings.posting.level = logging.WARNING
```

Example of the logs I mean:
```
[2022-08-19 14:44:51,164] azure.core.pipeline. [INFO    ] Response status: 200
Response headers:
    'Cache-Control': 'no-cache'
    'Pragma': 'no-cache'
    'Content-Type': 'application/json; charset=utf-8'
    'Expires': '-1'
    'x-ms-keyvault-region': 'eastus2'
    'x-ms-client-request-id': 'REDACTED'
    'x-ms-request-id': 'REDACTED'
    'x-ms-keyvault-service-version': '1.9.501.1'
    'x-ms-keyvault-network-info': 'conn_type=Subnet;addr=REDACTED;act_addr_fam=InterNetworkV6;'
    'X-Content-Type-Options': 'REDACTED'
    'Strict-Transport-Security': 'REDACTED'
    'Date': 'Fri, 19 Aug 2022 14:44:50 GMT'
    'Content-Length': '306'
[2022-08-19 14:44:51,668] azure.identity._cred [INFO    ] Environment is configured for ClientSecretCredential
[2022-08-19 14:44:51,668] azure.identity._cred [INFO    ] ManagedIdentityCredential will use IMDS
```

What would be the best way to remove those INFO entries from my operators log? The only messages I would like to see are the "prints" I have in my code.

Thank you!

**Comment by javiermarasco** [comment]
Any idea on how to remove of silence those [INFO] entries in the kopf logs?

Thank you!

**Comment by nolar** [comment]
Hi. The best way is to create an on-startup handler and configure Python's logging facility there to filter out undesired records using [Filters](https://docs.python.org/3/library/logging.html#filter-objects). The logger name is `kopf`.

**Comment by javiermarasco** [comment]
Hi @nolar , thank you for the response, it took me a few tries to get it working but there is what I did based on your recommendation, sharing in case someone else is having the same problem.

```
@kopf.on.startup()
def configure(logger, settings: kopf.OperatorSettings, **_):
    import logging
    azure_logger = logging.getLogger(name='azure.core.pipeline')
    azure_logger.setLevel('WARNING')
```



Those [INFO] events I was seeing were part of azure.core.pipeline, so setting that to WARNING removed the ones I was not willing to show.

Thank you again!
