### ISSUE TITLE
Disable changes on specific fields/objects possible?

### ISSUE THREAD

**Issue by davidp1404** [nolar/kopf#952]
### Keywords

kopf.on.update

### Problem

Hello and sorry if this is a silly or unconnected question. 
I've created a controller with your fantastic framework but I want to manage some CRD objects in a way that some of them couldn't be modified after creation, allowing only delete but not update. With the kopf.on.update handler I can just ignore doing anything but I can't avoid the state of the modified resource changes, breaking the desired state principle.
Does kopf provide any help to implement this logic?.
Thanks in advance.

**Comment by nolar** [comment]
Hello. All on-create/update/delete handlers only process things that have already happened, i.e. the object has been modified. If you want to prevent the modification (or creation/deletion), you have to look at the validation admission webhook — also supported by Kopf: https://kopf.readthedocs.io/en/stable/admission/

**Comment by davidp1404** [comment]
Hello Sergey, thanks very much for your answer, I will try creating an admission controller with kopf.
