### ISSUE TITLE
Replay resources doesn't work

### ISSUE THREAD

**Issue by davidp1404** [nolar/kopf#966]
### Problem

Hello, my use case manages two CRDs (DNS instance and DNS records). My operator allows removing the DNS instance leaving the associated DNS records present just in case it obeys to a temporary need. 
After recreating the DNS instance I planned to simply run "kubectl get dnsr -o yaml  | kubectl replace -f -" to reprocess them but I got a strange behaviour. The resources are created but the code associated to the operator is not executed.
After digging into the documentation I realized that  "kopf.zalando.org/last-handled-configuration" annotation explains this behaviour. 
My question then, is there any better approach than just asking to remove the annotations with something like this?
```
kubectl get dnsr -o yaml | \
yq 'del(.items[].metadata.annotations."kopf.zalando.org/last-handled-configuration")' - | \
kubectl replace -f -
```
Thanks for your help.

**Comment by nolar** [comment]
Hello. Thanks for asking. I probably do not fully understand the task, but I would say "no": if you copy the annotation, Kopf's perception of the object's status is also copied.

What you can do is develop your own diff-base storage. It can be based on the existing annotations storage or made anew. With this, you could take some arbitrary criteria (e.g. UUIDs) into consideration whether the annotation should be returned or ignored from the `fetch()` method. If you look at the source code of the storage, it is rather simple. See the docs here:

* https://kopf.readthedocs.io/en/stable/configuration/#handling-progress
* https://github.com/nolar/kopf/blob/1.36.0/kopf/_cogs/configs/diffbase.py#L106-L152

The storage can be anything — even MySQL/Postgres/Redis/S3 if you wish so, not only the annotations — as long as it persists the data over time.

**Comment by davidp1404** [comment]
Thanks very much Sergey for your guidance.
Regards,

-David
